In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('Forest_fire.csv')
data

Area  Oxygen  Temperature  Humidity  Fire Occurrence
0    Jharkand      40           45        20                1
1   Bangalore      50           30        10                1
2     Ecuador      10           20        70                0
3           a      60           45        70                1
4   Bangalore      30           48        10                1
5           c      50           15        30                0
6          de       5           35        35                0
7         asd       5           20        70                0
8     Ecuador      60           32        19                1
9           r      30           50        45                1
10          t      40           55        80                1
11          y      30           39       100                0
12   Jharkand      10           12        12                0
13  Bangalore      20           23        23                0
14    Ecuador      60           34        15                1
15     canada      80            4        68                0
16          c      25           56        79                1
17          c      12           45        90                0
18        asd      28           43        15                1
19        asd      26            0        32                0
20         ad      32           37        21                1
21       sasd      45           48        12                1
22        asd      56           15        65                0
23      asdas      67           45        33                1
24        das      78           49         8                1
25        das      89           45        18                1
26        ads      21           12        44                0
27        ads      11           20        59                0
28        asd       1           32        70                0
29        NaN       5           20        45                0
30        NaN      42           43        20                1
31        NaN      32           60        30                1
32        NaN       5           15         5                0
33        NaN      20           30         5                0
34        NaN      30           51         2                1
35        NaN      60           60        10                1
36        NaN      10           10        60                0
37        NaN       0           30         0                0
38        NaN      45           45        15                1

In [5]:
data = np.array(data)

In [6]:
data

array([['Jharkand', 40, 45, 20, 1],
       ['Bangalore', 50, 30, 10, 1],
       ['Ecuador', 10, 20, 70, 0],
       ['a', 60, 45, 70, 1],
       ['Bangalore', 30, 48, 10, 1],
       ['c', 50, 15, 30, 0],
       ['de', 5, 35, 35, 0],
       ['asd', 5, 20, 70, 0],
       ['Ecuador', 60, 32, 19, 1],
       ['r', 30, 50, 45, 1],
       ['t', 40, 55, 80, 1],
       ['y', 30, 39, 100, 0],
       ['Jharkand', 10, 12, 12, 0],
       ['Bangalore', 20, 23, 23, 0],
       ['Ecuador', 60, 34, 15, 1],
       ['canada', 80, 4, 68, 0],
       ['c', 25, 56, 79, 1],
       ['c', 12, 45, 90, 0],
       ['asd', 28, 43, 15, 1],
       ['asd', 26, 0, 32, 0],
       ['ad', 32, 37, 21, 1],
       ['sasd', 45, 48, 12, 1],
       ['asd', 56, 15, 65, 0],
       ['asdas', 67, 45, 33, 1],
       ['das', 78, 49, 8, 1],
       ['das', 89, 45, 18, 1],
       ['ads', 21, 12, 44, 0],
       ['ads', 11, 20, 59, 0],
       ['asd', 1, 32, 70, 0],
       [nan, 5, 20, 45, 0],
       [nan, 42, 43, 20, 1],
       [nan, 32, 60

In [7]:
x = data[:,1:-1]
y= data[:,-1]

In [8]:
x =x.astype('int')
y =y.astype('int')

In [9]:
y

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state =0)

In [12]:
x_train.shape

(31, 3)

In [13]:
y_train.shape

(31,)

In [14]:
x_test.shape

(8, 3)

In [15]:
y_test.shape

(8,)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
log_reg = LogisticRegression()

In [18]:
log_reg_train = log_reg.fit(x_train,y_train)

In [20]:
y_pred = log_reg_train.predict(x_test)

In [21]:
y_pred

array([1, 0, 0, 0, 1, 1, 1, 0])

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
accuracy_score(y_test,y_pred)

1.0

In [41]:
inputt=[int(x) for x in "45 32 60".split(' ')]

In [42]:
final=[np.array(inputt)]

In [43]:
final

[array([45, 32, 60])]

In [44]:
b =log_reg_train.predict_proba(final)

In [45]:
b

array([[0.62924669, 0.37075331]])

In [46]:
import pickle
import warnings

In [47]:
warnings.filterwarnings('ignore')

In [49]:
pickle.dump(log_reg_train,open('log_reg_forest_prevention_model.pkl','wb'))

In [54]:
model =pickle.load(open('log_reg_forest_prevention_model.pkl','rb'))

In [55]:
model

LogisticRegression()